services:
  ingress:
    image: nginx:alpine
    container_name: ingress
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../certs:/etc/nginx/ssl/all.chestno-game.all:ro
    ports:
      - 80:80
      - 443:443
    command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - dc-net
networks:
  dc-net:
    driver: bridge
    name: dc-net