name: Pg backup CI
on:
  push:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    if: contains(github.event.head_commit.message, '[backup]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Honest-games/honest-secrets
          token: ${{secrets.CI_PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Copy SSL cert
        run: |
          mkdir -p /tmp/deploy/ssl
          cp -r ssl/* /tmp/deploy/ssl
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{env.GITHUB_REPOSITORY}}
          token: ${{secrets.CI_PAT}}
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: pg-backup
          remote: /honest/pg-backup
          concurrency: 20
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            cd /honest/pg-backup
            
            export PG_HOST=pg
            export PG_PORT=5432
            export PG_USER=postgres
            export PG_PASS=${{env.PG_PASS}}
            export TG_BOT_TOKEN=${{env.BACKUP_TG_BOT_TOKEN}}
            export TG_CHAT_ID=${{env.BACKUP_TG_CHAT_ID}}

            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d