name: Ingress CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    if: contains(github.event.head_commit.message, '[ingress]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Honest-games/honest-secrets
          token: ${{secrets.CI_PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Copy SSL cert
        run: |
          mkdir -p /tmp/deploy/chestno-game.online/ssl
          cp -r ssl/chestno-game.online /tmp/deploy/chestno-game.online/ssl
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{env.GITHUB_REPOSITORY}}
          token: ${{secrets.CI_PAT}}
      - name: Set SSL cert
        run: |
          cp /tmp/deploy/chestno-game.online/ssl/* ./honest/ingress/ssl
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ingress
          remote: /honest/ingress
          concurrency: 20
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            cd /honest/ingress
            
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d