name: Jenkins CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    if: contains(github.event.head_commit.message, '[jenkins]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Honest-games/honest-secrets
          token: ${{secrets.CI_PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{env.GITHUB_REPOSITORY}}
          token: ${{secrets.CI_PAT}}
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: jenkins
          remote: /honest/jenkins
          concurrency: 20
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            cd /honest/jenkins
            # export N8N_HOST=${{env.N8N_HOST}}
            
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d