name: Postgres CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Honest-games/honest-secrets
          token: ${{secrets.CI_PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{env.GITHUB_REPOSITORY}}
          token: ${{secrets.CI_PAT}}
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: portainer
          remote: /honest/pg
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            cd /honest/pg
            export PG_PASS=${{env.PG_PASS}}
            export PGADMIN_USER=${{env.PGADMIN_USER}}
            export PGADMIN_PASSWORD=${{env.PGADMIN_PASSWORD}}
            
            docker-compose down --remove-orphans
            docker-compose up -d